### ISSUE TITLE
Import error with ooipy and obspy

### ISSUE THREAD

**Issue by FelixSchwock** [ooipy/ooipy#105]
When trying to import ooipy, I now get the following error. It seems that this error is caused by an update in the obspy package. Importing obspy (version 1.2.2) doesn't work for me either. Maybe we have to revert back to a previous obspy version so that ooipy is still usable.

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_25048/3356176566.py in <module>
----> 1 import obspy

~\anaconda3\envs\ooi\lib\site-packages\obspy\__init__.py in <module>
     37 
     38 # don't change order
---> 39 from obspy.core.utcdatetime import UTCDateTime  # NOQA
     40 from obspy.core.util import _get_version_string
     41 __version__ = _get_version_string(abbrev=10)

~\anaconda3\envs\ooi\lib\site-packages\obspy\core\__init__.py in <module>
    122 
    123 # don't change order
--> 124 from obspy.core.utcdatetime import UTCDateTime  # NOQA
    125 from obspy.core.util.attribdict import AttribDict  # NOQA
    126 from obspy.core.trace import Stats, Trace  # NOQA

~\anaconda3\envs\ooi\lib\site-packages\obspy\core\utcdatetime.py in <module>
     25 import numpy as np
     26 from obspy.core.compatibility import py3_round
---> 27 from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
     28 
     29 # Regular expression used in the init function of the UTCDateTime objects which

~\anaconda3\envs\ooi\lib\site-packages\obspy\core\util\__init__.py in <module>
     25 # import order matters - NamedTemporaryFile must be one of the first!
     26 from obspy.core.util.attribdict import AttribDict
---> 27 from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
     28                                   NATIVE_BYTEORDER, NETWORK_MODULES,
     29                                   NamedTemporaryFile, _read_from_plugin,

~\anaconda3\envs\ooi\lib\site-packages\obspy\core\util\base.py in <module>
     34 from pkg_resources import get_entry_info, iter_entry_points
     35 
---> 36 from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
     37 
     38 

~\anaconda3\envs\ooi\lib\site-packages\obspy\core\util\misc.py in <module>
    212 try:
    213     from numpy import loadtxt
--> 214     loadtxt(np.array([0]), ndmin=1)
    215 except TypeError:
    216     # otherwise redefine loadtxt

~\anaconda3\envs\ooi\lib\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, like)
   1084         # the need for decoding and estimate the number of columns.
   1085         for first_line in line_iter:
-> 1086             ncols = len(usecols or split_line(first_line))
   1087             if ncols:
   1088                 # Put first_line back.

~\anaconda3\envs\ooi\lib\site-packages\numpy\lib\npyio.py in split_line(line)
    975         """Chop off comments, strip, and split at delimiter."""
    976         for comment in comments:  # Much faster than using a single regex.
--> 977             line = line.split(comment, 1)[0]
    978         line = line.strip('\r\n')
    979         return line.split(delimiter) if line else []

AttributeError: 'numpy.int32' object has no attribute 'split'`

**Comment by FelixSchwock** [comment]
Also raised this issue here: https://github.com/obspy/obspy/issues/2940

**Comment by Molkree** [comment]
This is not due to obspy but due to the new NumPy version actually. See https://github.com/obspy/obspy/issues/2912 for more context. ObsPy folks are in the process of creating a new version to address this, you can track it here https://github.com/obspy/obspy/issues/2929.

**Comment by Molkree** [comment]
The proper way for OOIPy to avoid this error would be to:
- install ObsPy with the fix before they cut the release
Unfortunately, adding `git+https://github.com/obspy/obspy.git@maintenance_1.2.x#egg=obspy` to `requirements.txt` will not work for the regular install (such as `pip install ooipy` or `pip install .`) because of the hack in the `setup.py`. You read `requirements.txt` and just pass it as `install_requires` of `setuptools.setup`:
https://github.com/ooipy/ooipy/blob/097b9f275de15343735a9e4c416fca14b15ed9f4/setup.py#L8-L10
However this won't work with VCS links. There is a separate parameter for this called [`dependency_links`](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#dependencies-that-aren-t-in-pypi).
- require NumPy less than 1.22 `numpy<1.22`
This should be easier, just adding a new line to `requirements.txt` should be enough: `numpy<1.22`.

I'm not sure why `requirements.txt`/`setup_requires` were hacked like this, I don't think we need .txt file at all. Maybe this can be changed when [rewriting](https://setuptools.pypa.io/en/latest/userguide/quickstart.html) for PEP 517?

**Comment by John-Ragland** [comment]
I'll create a quick PR that implements the second solution you have mentioned, with a more long-term solution being implemented in  #106.
